Repository vanvalenlab/deepcell-label, pull requests merged in 2021-11, with the labels that each got.

#266 Update documentation
  README.md
  visualizer/src/Controls/ImageControls/FrameSlider.js
  visualizer/src/Controls/ImageControls/LabeledControls/FeatureSelect.js
  visualizer/src/Controls/ImageControls/LabeledControls/HighlightToggle.js
  visualizer/src/Controls/ImageControls/LabeledControls/OpacitySlider.js
  visualizer/src/Controls/ImageControls/LabeledControls/OutlineToggle.js
  visualizer/src/Controls/ImageControls/RawControls/ColorModeToggle.js
  visualizer/src/Controls/ImageControls/RawControls/GrayscaleControls.js
  visualizer/src/Controls/Segment/ActionButtons/ActionButton.js
  visualizer/src/Controls/Segment/ActionButtons/AutofitButton.js
  visualizer/src/Controls/Segment/ActionButtons/DeleteButton.js
  visualizer/src/Controls/Segment/ActionButtons/GrowButton.js
  visualizer/src/Controls/Segment/ActionButtons/ReplaceButton.js
  visualizer/src/Controls/Segment/ActionButtons/ShrinkButton.js
  visualizer/src/Controls/Segment/ActionButtons/SwapButton.js
  visualizer/src/Controls/Segment/SelectedPalette.js
  visualizer/src/Controls/Segment/ToolButtons/BrushButton.js
  visualizer/src/Controls/Segment/ToolButtons/EraserButton.js
  visualizer/src/Controls/Segment/ToolButtons/FloodButton.js
  visualizer/src/Controls/Segment/ToolButtons/SelectButton.js
  visualizer/src/Controls/Segment/ToolButtons/ThresholdButton.js
  visualizer/src/Controls/Segment/ToolButtons/ToolButton.js
  visualizer/src/Controls/Segment/ToolButtons/TrimButton.js
  visualizer/src/Controls/Segment/ToolButtons/WatershedButton.js
  visualizer/src/Controls/Segment/UndoRedo.js
  visualizer/src/Instructions/ActionInstructions.js
  visualizer/src/Instructions/CanvasInstructions.js
  visualizer/src/Instructions/DisplayInstructions.js
  visualizer/src/Instructions/Instructions.js
  visualizer/src/Instructions/Instructions.test.js
  visualizer/src/Instructions/SelectInstructions.js
  visualizer/src/Instructions/Shortcuts.js
  visualizer/src/Instructions/ToolInstructions.js
  visualizer/src/index.css
Labels: documentation

#277 Put a version ceiling on coveralls, 3.3.0 has a bug preventing builds.
  requirements-test.txt
Labels: dependencies, fix

#276 Upgrade to react-router v6
  visualizer/package.json
  visualizer/src/App.js
Labels: dependencies

#275 Reduce Docker image with slim base image and multi-stage builds & small code quality improvements.
  .dockerignore
  Dockerfile
  README.md
  deepcell_label/blueprints.py
  deepcell_label/conftest.py
  deepcell_label/exporters.py
  deepcell_label/exporters_test.py
  deepcell_label/imgutils_test.py
  deepcell_label/label.py
  deepcell_label/label_test.py
  deepcell_label/loaders_test.py
  deepcell_label/models.py
  requirements.txt
Labels: chore
