Repository vanvalenlab/deepcell-label, pull requests merged in 2023-01, with the labels that each got.

#398 Update URL to flake8 to fix precommit job.
  .github/workflows/precommithooks.yaml
  .pre-commit-config.yaml
Labels: chore

#397 BUG: fix bug when no cells on canvas.
  backend/deepcell_label/export.py
Labels: bug

#392 Implement cell types machine, basic controls, and canvas rendering
  backend/deepcell_label/loaders.py
  frontend/package.json
  frontend/src/Project/Canvas/ToolCanvas/AddCellTypeCanvas.js
  frontend/src/Project/Canvas/ToolCanvas/CellTypeCanvas.js
  frontend/src/Project/Canvas/ToolCanvas/ToolCanvas.js
  frontend/src/Project/DisplayControls/Cells/Selected/Selected.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeControls.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/AddCellTypeLabel.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/Cell.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellGrid.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordion.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordionList.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ColorIndicator.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/EditDeleteMenu.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/EditNameField.js
  frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/EditingPrompt.js
  frontend/src/Project/EditControls/CellTypeControls/index.js
  frontend/src/Project/EditControls/EditControls.js
  frontend/src/Project/EditControls/EditTabs.js
  frontend/src/Project/ProjectContext.js
  frontend/src/Project/service/edit/editCellTypesMachine.js
  frontend/src/Project/service/edit/editMachine.js
  frontend/src/Project/service/exportMachine.js
  frontend/src/Project/service/idbMachine.js
  frontend/src/Project/service/idbWebWorker.js
  frontend/src/Project/service/labels/cellTypesMachine.js
  frontend/src/Project/service/loadMachine.ts
  frontend/src/Project/service/loadMachine.typegen.ts
  frontend/src/Project/service/projectMachine.js
  frontend/yarn.lock
Labels: enhancement
